# Site settings
title: Distractions
header-img: img/home-bg.jpg
email: mail@davidamcclain.com
description: "Words by software engineer and person, David A McClain"
baseurl: ""
url: "http://davidamcclain.com"
twitter_username: davidamcclain
github_username:  uhhuhyeah
facebook_username:  davidamcclain
linkedin_username:  davidamcclain

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
